In [1]:
import numpy as np
import math
import pandas as pd
from sklearn.linear_model import LinearRegression

In [2]:
df = pd.read_csv('test_scores.csv')
df

name  math  cs
0   david    92  98
1   laura    56  68
2  sanjay    88  81
3     wei    70  80
4    jeff    80  83
5   aamir    49  52
6  venkat    65  66
7   virat    35  30
8  arthur    66  68
9    paul    67  73

In [3]:
reg = LinearRegression()

In [4]:
reg.fit(df[['math']], df['cs'])

LinearRegression()

In [5]:
m = reg.coef_
m

array([1.01773624])

In [6]:
c = reg.intercept_
c

1.9152193111569318

In [7]:
def predict():
    df = pd.read_csv('test_scores.csv')
    reg = LinearRegression()
    reg.fit(df[['math']], df['cs'])
    m = reg.coef_
    c = reg.intercept_
    return m, c

In [8]:
predict()

(array([1.01773624]), 1.9152193111569318)

In [9]:
def gradient_descent(x, y):
    m_current = c_current = 0
    iterations = 10000000
    n = len(x)
    learning_rate = 0.0001
    cost_previous = 0.0
    for i in range(iterations):
        y_predict = m * x + c
        cost = (1 / n) * sum([x ** 2 for x in (y - y_predict)])
        m_derivative = -(2 / n) * sum(x * (y - y_predict))
        c_derivative = -(2 / n) * sum(y - y_predict)
        m_current = m_current - learning_rate * m_derivative
        c_current = c_current - learning_rate * c_derivative
        if math.isclose(cost, cost_previous, rel_tol=1e-20):
            break
        cost_previous = cost
        print('m = {}, c = {}, cost = {}, iteration = {}'.format(m_current, c_current, cost, i))
    return m_current, c_current

In [10]:
df = pd.read_csv('test_scores.csv')
df

name  math  cs
0   david    92  98
1   laura    56  68
2  sanjay    88  81
3     wei    70  80
4    jeff    80  83
5   aamir    49  52
6  venkat    65  66
7   virat    35  30
8  arthur    66  68
9    paul    67  73

In [11]:
x = np.array(df.math)
y = np.array(df.cs)

In [12]:
x, y

(array([92, 56, 88, 70, 80, 49, 65, 35, 66, 67], dtype=int64),
 array([98, 68, 81, 80, 83, 52, 66, 30, 68, 73], dtype=int64))

In [13]:
m, c = gradient_descent(x, y)

m = -1.6029844118747863e-16, c = -2.557953848736361e-18, cost = 31.604511333529583, iteration = 0


In [14]:
m_predict, c_predict = predict()

In [15]:
print(m, c)
print(m_predict, c_predict)

-3.2059688237495726e-16 -5.115907697472722e-18
[1.01773624] 1.9152193111569318


In [16]:
import matplotlib.pyplot as plt