In [1]:
from sklearn.datasets import load_digits
import pandas as pd
import numpy as np

In [2]:
digits = load_digits()

In [3]:
dir(digits)

['DESCR', 'data', 'images', 'target', 'target_names']

In [4]:
df = pd.DataFrame(digits.data)
df.head()

0    1    2     3     4     5    6   ...   57   58    59    60    61   62   63
0  0.0  0.0  5.0  13.0   9.0   1.0  0.0  ...  0.0  6.0  13.0  10.0   0.0  0.0  0.0
1  0.0  0.0  0.0  12.0  13.0   5.0  0.0  ...  0.0  0.0  11.0  16.0  10.0  0.0  0.0
2  0.0  0.0  0.0   4.0  15.0  12.0  0.0  ...  0.0  0.0   3.0  11.0  16.0  9.0  0.0
3  0.0  0.0  7.0  15.0  13.0   1.0  0.0  ...  0.0  7.0  13.0  13.0   9.0  0.0  0.0
4  0.0  0.0  0.0   1.0  11.0   0.0  0.0  ...  0.0  0.0   2.0  16.0   4.0  0.0  0.0

[5 rows x 64 columns]

In [5]:
df['target'] = digits.target

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
(xtrain, xtest, ytrain, ytest) = train_test_split(digits.data, digits.target, test_size=0.2)

In [8]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()

In [9]:
lr.fit(xtrain, ytrain)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [10]:
lr.score(xtest, ytest)

0.5553399438827722

In [13]:
from sklearn.linear_model import LogisticRegression
lgr = LogisticRegression(max_iter=100000)

In [14]:
lgr.fit(xtrain, ytrain)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [15]:
lgr.score(xtest, ytest)

0.9722222222222222

In [16]:
from sklearn.tree import DecisionTreeClassifier

In [17]:
dtc = DecisionTreeClassifier()

In [18]:
dtc.fit(xtrain, ytrain)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [19]:
dtc.score(xtest, ytest)

0.8166666666666667

In [20]:
from sklearn.ensemble import RandomForestClassifier

In [22]:
rfc = RandomForestClassifier(max_features=.1)

In [23]:
rfc.fit(xtrain, ytrain)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features=0.1,
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [24]:
rfc.score(xtest, ytest)

0.9777777777777777

In [26]:
from sklearn.model_selection import KFold

In [28]:
kf = KFold()

In [29]:
for train_index, test_index in kf.split([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]):
  print(train_index, test_index)

[2 3 4 5 6 7 8 9] [0 1]
[0 1 4 5 6 7 8 9] [2 3]
[0 1 2 3 6 7 8 9] [4 5]
[0 1 2 3 4 5 8 9] [6 7]
[0 1 2 3 4 5 6 7] [8 9]


In [30]:
def get_score(model):
  model.fit(xtrain, ytrain)
  return model.score(xtest, ytest)

In [31]:
get_score(lr)

0.5553399438827722

In [32]:
get_score(lgr)

0.9722222222222222

In [33]:
get_score(dtc)

0.825

In [34]:
get_score(rfc)

0.9694444444444444

In [35]:
from sklearn.model_selection import StratifiedKFold

In [36]:
skf = StratifiedKFold()

In [37]:
score_lr = []
score_lgr = []
score_dtc = []
score_rfc = []

In [40]:
for train_index, test_index in skf.split(digits.data, digits.target):
    (xtrain, xtest, ytrain, ytest) = (digits.data[train_index], digits.data[test_index], digits.target[train_index], digits.target[test_index])
    score_lr.append(get_score(lr))
    score_lgr.append(get_score(lgr))
    score_dtc.append(get_score(dtc))
    score_rfc.append(get_score(rfc))

In [43]:
score_lr, score_lgr, score_dtc, score_rfc

([0.4821322809777912,
  0.552003594148794,
  0.569246389300946,
  0.5104744723295154,
  0.41688931380220434],
 [0.925,
  0.8777777777777778,
  0.9387186629526463,
  0.9331476323119777,
  0.8969359331476323],
 [0.7972222222222223,
  0.7361111111111112,
  0.8161559888579387,
  0.8328690807799443,
  0.7938718662952646],
 [0.9222222222222223,
  0.9027777777777778,
  0.9526462395543176,
  0.9749303621169917,
  0.924791086350975])

In [44]:
from sklearn.model_selection import cross_val_score

In [45]:
x = digits.data
y = digits.target

In [46]:
cross_val_score(lr, x, y)

array([0.48346048, 0.5583603 , 0.57534522, 0.5056632 , 0.40995457])

In [47]:
cross_val_score(lgr, x, y)

array([0.925     , 0.87777778, 0.93871866, 0.93314763, 0.89693593])