In [1]:
import numpy as np

In [2]:
a = np.arange(16).reshape(4, 4)

In [3]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [4]:
for row in a:
    for cell in row:
        print(cell)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


In [6]:
for cell in a.flatten():
    print(cell)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


In [7]:
for i in np.nditer(a, order='C'):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


In [8]:
for i in np.nditer(a, order='F'):
    print(i)

0
4
8
12
1
5
9
13
2
6
10
14
3
7
11
15


In [10]:
for i in np.nditer(a, order='F', flags=['external_loop']):
    print(i)

[ 0  4  8 12]
[ 1  5  9 13]
[ 2  6 10 14]
[ 3  7 11 15]


In [11]:
for i in np.nditer(a, order='C', flags=['external_loop']):
    print(i)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [14]:
for i in np.nditer(a, op_flags=['readwrite']):
    i[...] = i * i

In [15]:
a

array([[          0,           1,           0,  -773324799],
       [          0,  1291321345,           0,  1269825537],
       [          0, -1546649599,           0,   710410241],
       [          0, -1551368191,           0,   517996545]])

In [16]:
a = np.arange(16).reshape(4, 4)

In [17]:
for i in np.nditer(a, op_flags=['readwrite']):
    i[...] = i * i
a

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121],
       [144, 169, 196, 225]])

In [18]:
b = np.arange(4).reshape(4, 1)

In [19]:
b

array([[0],
       [1],
       [2],
       [3]])

In [20]:
a, b

(array([[  0,   1,   4,   9],
        [ 16,  25,  36,  49],
        [ 64,  81, 100, 121],
        [144, 169, 196, 225]]),
 array([[0],
        [1],
        [2],
        [3]]))

In [21]:
for x, y in np.nditer([a, b]):
    print(x, y)

0 0
1 0
4 0
9 0
16 1
25 1
36 1
49 1
64 2
81 2
100 2
121 2
144 3
169 3
196 3
225 3
