In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3, 4, 5])

In [3]:
a[0:2]

array([1, 2])

In [5]:
a[-1]

5

In [15]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [16]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
a[2, 2]

9

In [18]:
a[0:2, 2]

array([3, 6])

In [19]:
a[-1]

array([7, 8, 9])

In [20]:
a[-1, -1]

9

In [22]:
a[-1, 0:2]

array([7, 8])

In [23]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
a[0:3, 1]

array([2, 5, 8])

In [26]:
a[:, 1]

array([2, 5, 8])

In [28]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
for row in a:
    print(row)

[1 2 3]
[4 5 6]
[7 8 9]


In [32]:
for cell in a.flat:
    print(cell)

1
2
3
4
5
6
7
8
9


In [33]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
b = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])

In [36]:
b

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [37]:
b.shape

(4, 2)

In [38]:
b.ndim

2

In [39]:
b.reshape(2, 4)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [40]:
c = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [41]:
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [42]:
np.vstack((a, c))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
np.hstack((a, c))

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [7, 8, 9, 7, 8, 9]])

In [46]:
d = []

In [47]:
for i in range(15):
    d.append(i)

In [48]:
d

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]

In [52]:
e = []
for i in range(15, 30):
    e.append(i)

In [53]:
e

[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]

In [54]:
len(e)

15

In [55]:
len(d)

15

In [56]:
a = np.array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14],
             [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [57]:
len(a)

2

In [58]:
a.shape

(2, 15)

In [59]:
a.reshape(30)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [60]:
a.reshape(5, 6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [61]:
np.hsplit(a, 3)

[array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]]),
 array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]]),
 array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]])]

In [62]:
print(np.hsplit(a, 3))

[array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]]), array([[ 5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24]]), array([[10, 11, 12, 13, 14],
       [25, 26, 27, 28, 29]])]


In [64]:
np.vsplit(a, 2)

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])]

In [65]:
a = np.arange(12).reshape(3, 4)

In [66]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [67]:
b = a > 4

In [68]:
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [69]:
a[b]

array([ 5,  6,  7,  8,  9, 10, 11])

In [70]:
a[b] = -1

In [71]:
a

array([[ 0,  1,  2,  3],
       [ 4, -1, -1, -1],
       [-1, -1, -1, -1]])