In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
a[2]

3

In [6]:
a = np.array([[1, 2], [3, 4]])

In [7]:
a.ndim

2

In [8]:
a.itemsize

4

In [19]:
a = np.array([[1, 2], [3, 4]], dtype=np.float64)

In [20]:
a

array([[1., 2.],
       [3., 4.]])

In [21]:
a = np.array([1.0, 2.0, 3.0, 4.0])

In [22]:
a.itemsize

8

In [23]:
a.size

4

In [24]:
a.shape

(4,)

In [25]:
a = np.array([[1, 2], [3, 4]], dtype=np.complex_)

In [26]:
a

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [27]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [29]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [30]:
l = range(10)

In [31]:
for i in l:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [32]:
l = np.arange(10)

In [33]:
for i in l:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [34]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [35]:
np.linspace(0, 10, 20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [36]:
a = np.array([[1, 2], [3, 4], [5, 6]])

In [37]:
a.shape

(3, 2)

In [38]:
a.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
a.flatten()

array([1, 2, 3, 4, 5, 6])

In [42]:
a.ravel()

array([1, 2, 3, 4, 5, 6])

In [41]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [43]:
a.min()

1

In [44]:
a.max()

6

In [45]:
a.sum()

21

In [46]:
a.sum(axis=0)

array([ 9, 12])

In [47]:
a.sum(axis=1)

array([ 3,  7, 11])

In [48]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974]])

In [49]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [50]:
np.std(a)

1.707825127659933

In [51]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

In [52]:
a

array([[1, 2],
       [3, 4]])

In [53]:
b

array([[5, 6],
       [7, 8]])

In [54]:
a + b

array([[ 6,  8],
       [10, 12]])

In [55]:
a * b

array([[ 5, 12],
       [21, 32]])

In [56]:
a / b

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [58]:
a.dot(b)

array([[19, 22],
       [43, 50]])